# These are supported funding model platforms

# GitHub Sponsors
github: # Replace with your GitHub username

# Patreon
patreon: # Replace with your Patreon username

# Open Collective
open_collective: # Replace with your Open Collective username

# Ko-fi
ko_fi: # Replace with your Ko-fi username

# Tidelift
tidelift: # Replace with your Tidelift platform/project

# Community Bridge
community_bridge: # Replace with your Community Bridge project-name

# Liberapay
liberapay: # Replace with your Liberapay username

# IssueHunt
issuehunt: # Replace with your IssueHunt username

# Otechie
otechie: # Replace with your Otechie username

# Custom sponsorship URL
custom: # Replace with your custom sponsorship URL
