labels:
  - name: bug
    color: d73a49
    description: "Something isn't working"
  - name: enhancement
    color: a2eeef
    description: "New feature or request"
  - name: security
    color: b60205
    description: "Security vulnerability"
  - name: documentation
    color: 0075ca
    description: "Improvements or additions to documentation"
  - name: "good first issue"
    color: 7057ff
    description: "Good for newcomers"
  - name: "help wanted"
    color: 008672
    description: "Extra attention is needed"
