# Kong declarative configuration for Sira
# This file defines all Kong entities (services, routes, plugins, etc.)

# Upstream targets for Sira
upstreams:
  - name: ai-gateway-upstream
    targets:
      - target: ai-gateway:8080
        weight: 100
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 5
        interval: 30
        successes: 2
        failures: 3

# Services
services:
  - name: ai-gateway-service
    url: http://ai-gateway-upstream
    routes:
      - name: ai-chat-completions
        paths:
          - /api/v1/ai/chat/completions
        methods:
          - POST
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-API-Key
                - X-Requested-With
                - Authorization
              credentials: true

          - name: key-auth
            config:
              key_names:
                - x-api-key
              hide_credentials: true

          - name: ai-rate-limit
            config:
              window_ms: 900000
              max_requests: 100
              max_tokens: 10000

          - name: ai-cache
            config:
              ttl: 300
              max_size: 1000

          - name: ai-circuit-breaker
            config:
              timeout: 30000
              error_threshold_percentage: 50
              reset_timeout: 30000

          - name: ai-tracing
            config:
              service_name: ai-gateway
              service_version: "2.0.0"
              environment: production
              exporter: jaeger
              sample_rate: 1.0

          - name: ai-router
            config:
              timeout: 30000

      - name: ai-embeddings
        paths:
          - /api/v1/ai/embeddings
        methods:
          - POST
        plugins:
          - name: cors
          - name: key-auth
          - name: ai-rate-limit
          - name: ai-cache
          - name: ai-circuit-breaker
          - name: ai-tracing
          - name: ai-router

      - name: ai-models
        paths:
          - /api/v1/ai/models
        methods:
          - GET
        plugins:
          - name: cors
          - name: key-auth
          - name: ai-rate-limit

  - name: kong-admin-service
    url: http://kong:8001
    routes:
      - name: kong-admin
        paths:
          - /kong-admin
        strip_path: true
        plugins:
          - name: cors

# Consumers (API clients)
consumers:
  - username: ai-gateway-client
    custom_id: ai-gateway-client-001
    keyauth_credentials:
      - key: test-api-key-123

# Plugins configuration
plugins:
  - name: prometheus
    service: ai-gateway-service
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  - name: request-transformer
    service: ai-gateway-service
    config:
      add:
        headers:
          - "X-Gateway: Kong"
          - "X-Request-ID:$(uuid)"

  - name: response-transformer
    service: ai-gateway-service
    config:
      add:
        headers:
          - "X-Powered-By: AI-Gateway"
          - "X-Response-Time:$(latency)"

# Global plugins
global_plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - X-API-Key
        - Authorization
      credentials: true

  - name: prometheus
    config:
      per_consumer: false

  - name: request-transformer
    config:
      add:
        headers:
          - "X-Forwarded-Proto: $(scheme)"
          - "X-Forwarded-Host: $(host)"
          - "X-Real-IP: $(remote_addr)"
