name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[Feature] '
labels: ['enhancement', 'feature-request']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for suggesting a new feature! We love hearing from our community about ways to improve the project.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you would like to see.
      placeholder: What would you like to be able to do?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve? What's the use case?
      placeholder: Describe the problem this feature would solve.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution.
      placeholder: How would you like this feature to work?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other solutions have you considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/Blocking

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small changes)
        - Medium (moderate changes)
        - Complex (significant changes)
        - Very Complex (architectural changes)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: This feature would benefit other users
          required: true
        - label: I am willing to help implement this feature
        - label: I can provide more details or mockups if needed
